template = "https://github.com/giellalt/template-lang-und"
rev_id = 332
template_sha = "517a754a9d968919fdaa1ed6e00d20145fac402c"

[replacements]
__GLOTTOLOG_ID__ = "tata1255"
__REPO__ = "lang-tat"
__UND2C__ = "tt"
__UNDEFINED__ = "Tatar"
__UND__ = "tat"
