template = "https://github.com/giellalt/template-lang-und"
rev_id = 296
template_sha = "879b03783ce7c34cc6b4dfc240164614f484a26e"

[replacements]
__GLOTTOLOG_ID__ = "tata1255"
__REPO__ = "lang-tat"
__UND2C__ = "tt"
__UNDEFINED__ = "Tatar"
__UND__ = "tat"
