[package]
name = "tat"
human_name = "Tatar"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.tat]
filename = "tt-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-tat"
platform = "windows"
uuid = "A38E50C1-3C00-4B3E-8E5B-202DBC13A5E4"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.tt"
package = "speller-tat"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-tat-mso"
platform = "windows"
uuid = "2E9F6AAD-163D-492B-93A8-CDE0A1E04712"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-tat"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
